[project]
name = "ourametry-py"
version = "0.1.0"
description = "A simple web server for loading Oura metrics into PostgreSQL."
authors = [
    {name = "Mason Yu",email = "masonliyu@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.13, <4.0"
dependencies = [
    "oura-api-documentation-client @ file:///Users/requious/Projects/python/ourametry-py/api/oura",
    "django (>=5.1.6,<6.0.0)",
    "djangorestframework (>=3.15.2,<4.0.0)",
    "httpx (>=0.28.1,<0.29.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
